
public class AccountHandler {
public accounthandler(){}
public static Account insertNewAccountnew()
{
string s;
string k;
//testinggg
          string sri;
     Account act = New Account();
        act.Name = 'sri';
    try {
  
        insert act;
        }
    catch (DmlException e) {

       return null;
                           }
    return act;
}
public static Account insertNewAccount()
{
string s;
string k;
//testinggg
          string sri;
     Account act = New Account();
        act.Name = 'sri';
    try {
  
        insert act;
        }
    catch (DmlException e) {

       return null;
                           }
    return act;
}
//test
public static Account insertNewAccount1()
{

          string sri;
     Account act = New Account();
        act.Name = 'sri';
    try {
  
        insert act;
        }
    catch (DmlException e) {

       return null;
                           }
    return act;
}
public static Account insertNewAccount3()
{

          string sri;
     Account act = New Account();
        act.Name = 'sri';
    try {
  
        insert act;
        }
    catch (DmlException e) {

       return null;
                           }
    return act;
}

///newtesttt
}
